# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/tijsv/Documents/UA sem2/DigitaleElektronica/Sessie8/Opdracht6/Opdracht6.srcs/sources_1/ip/clk_wiz_5MHz/clk_wiz_5MHz.xci
# IP: The module: 'clk_wiz_5MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/tijsv/Documents/UA sem2/DigitaleElektronica/Sessie8/Opdracht6/Opdracht6.srcs/sources_1/ip/clk_wiz_5MHz/clk_wiz_5MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_5MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/tijsv/Documents/UA sem2/DigitaleElektronica/Sessie8/Opdracht6/Opdracht6.srcs/sources_1/ip/clk_wiz_5MHz/clk_wiz_5MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_5MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/tijsv/Documents/UA sem2/DigitaleElektronica/Sessie8/Opdracht6/Opdracht6.srcs/sources_1/ip/clk_wiz_5MHz/clk_wiz_5MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_5MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/tijsv/Documents/UA sem2/DigitaleElektronica/Sessie8/Opdracht6/Opdracht6.srcs/sources_1/ip/clk_wiz_5MHz/clk_wiz_5MHz.xci
# IP: The module: 'clk_wiz_5MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/tijsv/Documents/UA sem2/DigitaleElektronica/Sessie8/Opdracht6/Opdracht6.srcs/sources_1/ip/clk_wiz_5MHz/clk_wiz_5MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_5MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/tijsv/Documents/UA sem2/DigitaleElektronica/Sessie8/Opdracht6/Opdracht6.srcs/sources_1/ip/clk_wiz_5MHz/clk_wiz_5MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_5MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/tijsv/Documents/UA sem2/DigitaleElektronica/Sessie8/Opdracht6/Opdracht6.srcs/sources_1/ip/clk_wiz_5MHz/clk_wiz_5MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_5MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
