# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/tijsv/Documents/UAsem2/DigitaleElektronica/Sessie8/project_teller/project_teller.cache/wt [current_project]
set_property parent.project_path D:/tijsv/Documents/UAsem2/DigitaleElektronica/Sessie8/project_teller/project_teller.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/tijsv/Documents/UAsem2/DigitaleElektronica/Sessie8/project_teller/project_teller.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib D:/tijsv/Documents/UAsem2/DigitaleElektronica/Sessie8/Opdracht6/Opdracht6.srcs/sources_1/new/Teller.vhd
read_ip -quiet D:/tijsv/Documents/UAsem2/DigitaleElektronica/Sessie8/project_teller/project_teller.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/tijsv/Documents/UAsem2/DigitaleElektronica/Sessie8/project_teller/project_teller.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/tijsv/Documents/UAsem2/DigitaleElektronica/Sessie8/project_teller/project_teller.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/tijsv/Documents/UAsem2/DigitaleElektronica/Sessie8/project_teller/project_teller.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/tijsv/Documents/UAsem2/DigitaleElektronica/digilent-xdc-master/Nexys-4-DDR-Master.xdc
set_property used_in_implementation false [get_files D:/tijsv/Documents/UAsem2/DigitaleElektronica/digilent-xdc-master/Nexys-4-DDR-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Teller -part xc7a100tcsg324-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Teller.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Teller_utilization_synth.rpt -pb Teller_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
